spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:C:/Nauka/PrzyszlyProgramista/Java/Projekty/Cwiczenia/TaskManager/task-db'
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TaskManagerApp'
  resource: 'task-manager-app-client'
  public-client: true